version: '3.8'


services:
  mysql:
    restart: on-failure
    image: mysql:8
    container_name: mysql_pfairplay
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${DATASOURCE_DATABASE}
      MYSQL_TCP_PORT: ${DATASOURCE_TCP_PORT}
    ports:
      - "${DATASOURCE_TCP_PORT}:${DATASOURCE_TCP_PORT}"
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1' ]
      interval: 10s
      timeout: 2s
      retries: 100

  api:
    restart: on-failure
    build: .
    container_name: api_server_pfairplay
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
