version: '3.8'

services:
  mysql:
    restart: always
    image: mysql:8
    container_name: mysql_pfairplay
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    ports:
      - "${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}"

  api:
    restart: always
    build: ../..
    container_name: api_server_pfairplay
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: ${MYSQL_URL}
      DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
