spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pfairplay
    username: ryoo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    open-in-view: false