name: Build Project by docker-compose and deploy dokcer-image to docker-hub
on:
  pull_request:
    branches:
      - main
#jobs:
#  build-deploy-image:
#    runs-on: self-hosted
#    environment: dev
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name : Test project
#        run: ./gradlew test
#
#      - name: Build docker-image
#        run: docker compose build
#        env:
#          DATASOURCE_DATABASE: ${{ secrets.MYSQL_DATABASE }}
#          DATASOURCE_TCP_PORT: ${{ secrets.MYSQL_TCP_PORT }}
#          DATASOURCE_URL: ${{ secrets.MYSQL_URL }}
#          DATASOURCE_USERNAME: ${{ secrets.MYSQL_USERNAME }}
#          DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
#
#      - name: Log in to docker-hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Push docker-image to docker-hub
#        run: |
#          docker tag pfairplay-api ryoodg/pfairplay-api:latest
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfairplay-api:latest

