name: Build Project by docker-compose and deploy dokcer-image to docker-hub
on:
  push:
    branches:
      - test-cicd
jobs:
  build-deploy-image:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Build docker-image
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_TCP_PORT: ${{ secrets.MYSQL_TCP_PORT }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: docker compose build


      - name: Log in to docker-hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker-image to docker-hub
        run: |
          docker tag pfairplay-api ryoodg/pfairplay-api:1.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfairplay-api:latest

